SET FOREIGN_KEY_CHECKS=0;--> statement-breakpoint
DROP TABLE `capture_errors`;--> statement-breakpoint
DROP TABLE `capture_logs`;--> statement-breakpoint
DROP TABLE `cnpj_monitor_config`;--> statement-breakpoint
DROP TABLE `cnpj_monitor_events`;--> statement-breakpoint
DROP TABLE `contract_balance_movements`;--> statement-breakpoint
DROP TABLE `contract_extensions`;--> statement-breakpoint
DROP TABLE `contract_reajustes`;--> statement-breakpoint
DROP TABLE `contrato_reajustes`;--> statement-breakpoint
DROP TABLE `contratos`;--> statement-breakpoint
DROP TABLE `duplicate_detection_results`;--> statement-breakpoint
DROP TABLE `duplicate_detection_runs`;--> statement-breakpoint
DROP TABLE `duplicate_merge_history`;--> statement-breakpoint
DROP TABLE `edital_analyses`;--> statement-breakpoint
DROP TABLE `equivalenceProfiles`;--> statement-breakpoint
DROP TABLE `equivalenceResults`;--> statement-breakpoint
DROP TABLE `equivalenceSessions`;--> statement-breakpoint
DROP TABLE `estoque`;--> statement-breakpoint
DROP TABLE `estoque_reservas`;--> statement-breakpoint
DROP TABLE `executive_decision_factors`;--> statement-breakpoint
DROP TABLE `executive_decisions`;--> statement-breakpoint
DROP TABLE `extractedAttributes`;--> statement-breakpoint
DROP TABLE `gov_licitation_items`;--> statement-breakpoint
DROP TABLE `gov_licitations`;--> statement-breakpoint
DROP TABLE `gov_participation_history`;--> statement-breakpoint
DROP TABLE `image_auto_link_history`;--> statement-breakpoint
DROP TABLE `keyword_monitor_config`;--> statement-breakpoint
DROP TABLE `keyword_monitor_events`;--> statement-breakpoint
DROP TABLE `licitacaoItens`;--> statement-breakpoint
DROP TABLE `licitacaoMatch`;--> statement-breakpoint
DROP TABLE `licitacao_resultados`;--> statement-breakpoint
DROP TABLE `licitacaoSyncLogs`;--> statement-breakpoint
DROP TABLE `licitacoes_descobertas`;--> statement-breakpoint
DROP TABLE `match_feedback_v2`;--> statement-breakpoint
DROP TABLE `notification_history`;--> statement-breakpoint
DROP TABLE `notification_webhooks`;--> statement-breakpoint
DROP TABLE `oportunidadesLicitacao`;--> statement-breakpoint
DROP TABLE `org_history_events`;--> statement-breakpoint
DROP TABLE `pricing_configs`;--> statement-breakpoint
DROP TABLE `pricing_history`;--> statement-breakpoint
DROP TABLE `product_images`;--> statement-breakpoint
DROP TABLE `productMetadata`;--> statement-breakpoint
DROP TABLE `publicPriceHistory`;--> statement-breakpoint
DROP TABLE `quotation_items`;--> statement-breakpoint
DROP TABLE `quotations`;--> statement-breakpoint
DROP TABLE `radarKeywords`;--> statement-breakpoint
DROP TABLE `radarOpportunities`;--> statement-breakpoint
DROP TABLE `radarSources`;--> statement-breakpoint
DROP TABLE `radarSyncLogs`;--> statement-breakpoint
DROP TABLE `regras_tributarias`;--> statement-breakpoint
DROP TABLE `scrape_enrichment_log`;--> statement-breakpoint
DROP TABLE `scrape_errors`;--> statement-breakpoint
DROP TABLE `scrape_jobs`;--> statement-breakpoint
DROP TABLE `scrape_profiles`;--> statement-breakpoint
DROP TABLE `scrape_results`;--> statement-breakpoint
DROP TABLE `supplier_capture_configs`;--> statement-breakpoint
DROP TABLE `supplierConnectors`;--> statement-breakpoint
DROP TABLE `supplier_credentials`;--> statement-breakpoint
DROP TABLE `supplier_imports`;--> statement-breakpoint
ALTER TABLE `proposals` DROP COLUMN `regrasTributariasId`;--> statement-breakpoint
SET FOREIGN_KEY_CHECKS=1;--> statement-breakpoint