CREATE TABLE `integration_cache` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `source` VARCHAR(64) NOT NULL,
  `operation` VARCHAR(128) NOT NULL,
  `cache_key` VARCHAR(191) NOT NULL,
  `source_url` VARCHAR(2048) NULL,
  `connector_version` VARCHAR(64) NULL,
  `schema_version` VARCHAR(64) NULL,
  `status_code` INT NOT NULL DEFAULT 200,
  `content_type` VARCHAR(128) NULL,
  `etag` VARCHAR(512) NULL,
  `payload_hash` VARCHAR(64) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `fetched_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` TIMESTAMP NOT NULL,
  `last_accessed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `access_count` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_integration_cache_source_operation_key` (`source`, `operation`, `cache_key`),
  KEY `idx_integration_cache_expires_at` (`expires_at`),
  KEY `idx_integration_cache_source_fetched_at` (`source`, `fetched_at`)
);
