-- Migration 0023 — Módulo AgenticSeek (prospecção automatizada de licitações)
-- Tabelas: agenticseek_buscas e agenticseek_resultados.
-- Idempotente: usa CREATE TABLE IF NOT EXISTS e CREATE INDEX IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS agenticseek_buscas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NULL,
  objetivo TEXT NOT NULL,
  keywords VARCHAR(1024) NULL,
  uf VARCHAR(2) NULL,
  municipio VARCHAR(128) NULL,
  diasAtras INT NULL,
  modalidades VARCHAR(64) NULL,
  status ENUM('pendente','executando','concluida','erro','cancelada') NOT NULL DEFAULT 'pendente',
  totalResultados INT NOT NULL DEFAULT 0,
  totalValidados INT NOT NULL DEFAULT 0,
  erroMensagem TEXT NULL,
  custoEstimadoBrl DECIMAL(12,4) NULL,
  custoEstimadoUsd DECIMAL(12,4) NULL,
  tempoExecucaoMs INT NULL,
  startedAt TIMESTAMP NULL,
  completedAt TIMESTAMP NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_agenticseek_status (status),
  KEY idx_agenticseek_user (userId),
  KEY idx_agenticseek_created (createdAt),
  CONSTRAINT fk_agenticseek_busca_user FOREIGN KEY (userId) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agenticseek_resultados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  buscaId INT NOT NULL,
  fonte ENUM('pncp') NOT NULL DEFAULT 'pncp',
  editalId VARCHAR(256) NULL,
  numeroControlePncp VARCHAR(64) NULL,
  orgao VARCHAR(512) NULL,
  cnpjOrgao VARCHAR(20) NULL,
  uf VARCHAR(2) NULL,
  municipio VARCHAR(128) NULL,
  modalidade VARCHAR(128) NULL,
  objeto TEXT NULL,
  dataPublicacao VARCHAR(32) NULL,
  dataAbertura VARCHAR(32) NULL,
  dataEncerramento VARCHAR(32) NULL,
  valorEstimado DECIMAL(15,2) NULL,
  link TEXT NULL,
  cnpjValido TINYINT(1) NULL,
  cnpjNaturezaJuridica VARCHAR(256) NULL,
  cnpjCnae VARCHAR(32) NULL,
  orgaoCompativel TINYINT(1) NULL,
  orgaoCompatibilidadeNota TEXT NULL,
  relevanceScore INT NULL,
  relevanceJustificativa TEXT NULL,
  validated TINYINT(1) NOT NULL DEFAULT 0,
  validationErrors JSON NULL,
  rawData JSON NULL,
  funilOportunidadeId INT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_agenticseek_result_busca (buscaId),
  KEY idx_agenticseek_result_edital (editalId),
  KEY idx_agenticseek_result_cnpj (cnpjOrgao),
  KEY idx_agenticseek_result_score (relevanceScore),
  CONSTRAINT fk_agenticseek_result_busca FOREIGN KEY (buscaId) REFERENCES agenticseek_buscas (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
