import { useMemo, useState } from "react";
import { CircleDollarSign, Loader2, Plus, ReceiptText, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { formatBRL, formatDateBR } from "@/lib/format";
import ControleFinanceiro from "./ControleFinanceiro";

type Tab = "movimentos" | "receber" | "pagar" | "fluxo";
const parseMoney = (value: string) => Number(value.replace(/\./g, "").replace(",", ".")) || 0;

export default function FinanceiroCentral() {
  const params = useMemo(() => new URLSearchParams(window.location.search), []);
  const targetNf = Number(params.get("nf"));
  const targetPayable = Number(params.get("pagar"));
  const initial: Tab = Number.isInteger(targetNf) && targetNf > 0 ? "receber" : Number.isInteger(targetPayable) && targetPayable > 0 ? "pagar" : "movimentos";
  const [tab, setTab] = useState<Tab>(initial);
  return <div className="space-y-5">
    <section className="mx-auto max-w-7xl rounded-2xl bg-blue-950 p-5 text-white"><div className="flex items-start gap-3"><CircleDollarSign size={26} className="mt-0.5" /><div><p className="m-0 text-[10px] font-black uppercase tracking-[0.16em] text-blue-200">Fonte financeira única</p><h1 className="mb-1 mt-1 text-2xl font-black">Financeiro</h1><p className="m-0 text-sm text-blue-100">Movimentações, notas a receber, contas a pagar e fluxo projetado no mesmo ambiente.</p></div></div></section>
    <div className="mx-auto flex max-w-7xl flex-wrap gap-2 border-b border-slate-200 pb-3"><TabButton active={tab === "movimentos"} onClick={() => setTab("movimentos")} label="Movimentações" /><TabButton active={tab === "receber"} onClick={() => setTab("receber")} label="A receber" /><TabButton active={tab === "pagar"} onClick={() => setTab("pagar")} label="A pagar" /><TabButton active={tab === "fluxo"} onClick={() => setTab("fluxo")} label="Fluxo projetado" /></div>
    {tab === "movimentos" && <ControleFinanceiro />}
    {tab === "receber" && <Receivables targetId={targetNf} />}
    {tab === "pagar" && <Payables targetId={targetPayable} />}
    {tab === "fluxo" && <Cashflow />}
  </div>;
}

function Receivables({ targetId }: { targetId: number }) {
  const utils = trpc.useUtils(); const query = trpc.posVenda.notas.useQuery(); const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ numero: "", orgao: "", valorBruto: "", retencoes: "", dataEmissao: new Date().toISOString().slice(0,10), vencimento: "", funilId: "" });
  const refresh = async () => Promise.all([utils.posVenda.notas.invalidate(), utils.agenda.proximos.invalidate(), utils.opportunities.list.invalidate(), utils.opportunities.summary.invalidate()]);
  const save = trpc.posVenda.salvarNota.useMutation({ onSuccess: async () => { setOpen(false); await refresh(); toast.success("Nota registrada."); }, onError: (e) => toast.error(e.message) });
  const paid = trpc.posVenda.marcarNotaPaga.useMutation({ onSuccess: async () => { await refresh(); toast.success("Recebimento registrado."); }, onError: (e) => toast.error(e.message) });
  const opportunities = trpc.opportunities.list.useQuery();
  return <Section title="Notas e recebimentos" icon={<ReceiptText size={18} />} action={<button onClick={() => setOpen((v) => !v)} className="inline-flex items-center gap-1 rounded-lg bg-blue-950 px-3 py-2 text-xs font-bold text-white"><Plus size={13}/> Registrar NF</button>}>
    {open && <div className="mb-4 grid gap-3 rounded-xl border border-blue-100 bg-blue-50/40 p-4 md:grid-cols-3"><Field label="NF *"><input value={form.numero} onChange={(e)=>setForm({...form,numero:e.target.value})} className={INPUT}/></Field><Field label="Órgão *"><input value={form.orgao} onChange={(e)=>setForm({...form,orgao:e.target.value})} className={INPUT}/></Field><Field label="Valor bruto *"><input value={form.valorBruto} onChange={(e)=>setForm({...form,valorBruto:e.target.value})} className={INPUT}/></Field><Field label="Retenções"><input value={form.retencoes} onChange={(e)=>setForm({...form,retencoes:e.target.value})} className={INPUT}/></Field><Field label="Emissão"><input type="date" value={form.dataEmissao} onChange={(e)=>setForm({...form,dataEmissao:e.target.value})} className={INPUT}/></Field><Field label="Previsão recebimento"><input type="date" value={form.vencimento} onChange={(e)=>setForm({...form,vencimento:e.target.value})} className={INPUT}/></Field><Field label="Oportunidade"><select value={form.funilId} onChange={(e)=>setForm({...form,funilId:e.target.value})} className={INPUT}><option value="">Sem vínculo</option>{(opportunities.data??[]).filter((o)=>o.macroEtapa==="execucao").map((o)=><option key={o.id} value={o.id}>#{o.id} {o.titulo}</option>)}</select></Field><div className="flex items-end md:col-span-2"><button disabled={save.isPending||!form.numero||!form.orgao||parseMoney(form.valorBruto)<=0} onClick={()=>save.mutate({numero:form.numero,orgao:form.orgao,valorBruto:parseMoney(form.valorBruto),retencoes:parseMoney(form.retencoes)||undefined,dataEmissao:form.dataEmissao,vencimento:form.vencimento||undefined,funilId:form.funilId?Number(form.funilId):undefined})} className="rounded-lg bg-blue-950 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Salvar</button></div></div>}
    {query.isLoading?<Loading/>:<div className="space-y-2">{(query.data??[]).map((row)=><div key={row.id} className={`flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center ${row.id===targetId?"border-blue-400 bg-blue-50":"border-slate-200"}`}><div className="min-w-0 flex-1"><div className="text-sm font-bold text-slate-900">NF {row.numero} · {row.orgao}</div><div className="mt-1 text-xs text-slate-500">{formatBRL(Number(row.valorBruto))}{row.vencimento?` · vence ${formatDateBR(row.vencimento)}`:""} · {row.status}</div></div>{!row.recebidoEm&&row.status!=="cancelada"&&<button disabled={paid.isPending} onClick={()=>paid.mutate({id:row.id})} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-bold text-emerald-700">Marcar recebido</button>}</div>)}</div>}
  </Section>;
}

function Payables({ targetId }: { targetId: number }) {
  const utils=trpc.useUtils(); const query=trpc.posVenda.contasPagar.useQuery(); const [open,setOpen]=useState(false);
  const [form,setForm]=useState({descricao:"",credor:"",categoria:"fornecedor" as "fornecedor"|"frete"|"imposto"|"taxa"|"despesa",valor:"",vencimento:""});
  const save=trpc.posVenda.salvarContaPagar.useMutation({onSuccess:async()=>{setOpen(false);await Promise.all([utils.posVenda.contasPagar.invalidate(),utils.agenda.proximos.invalidate()]);toast.success("Conta registrada.");},onError:(e)=>toast.error(e.message)});
  const paid=trpc.posVenda.marcarContaPaga.useMutation({onSuccess:async()=>{await Promise.all([utils.posVenda.contasPagar.invalidate(),utils.agenda.proximos.invalidate()]);toast.success("Pagamento registrado.");},onError:(e)=>toast.error(e.message)});
  return <Section title="Contas a pagar" icon={<WalletCards size={18}/>} action={<button onClick={()=>setOpen((v)=>!v)} className="inline-flex items-center gap-1 rounded-lg bg-blue-950 px-3 py-2 text-xs font-bold text-white"><Plus size={13}/> Nova conta</button>}>
    {open&&<div className="mb-4 grid gap-3 rounded-xl border border-blue-100 bg-blue-50/40 p-4 md:grid-cols-3"><Field label="Descrição *"><input value={form.descricao} onChange={(e)=>setForm({...form,descricao:e.target.value})} className={INPUT}/></Field><Field label="Credor"><input value={form.credor} onChange={(e)=>setForm({...form,credor:e.target.value})} className={INPUT}/></Field><Field label="Categoria"><select value={form.categoria} onChange={(e)=>setForm({...form,categoria:e.target.value as typeof form.categoria})} className={INPUT}><option value="fornecedor">Fornecedor</option><option value="frete">Frete</option><option value="imposto">Imposto</option><option value="taxa">Taxa</option><option value="despesa">Despesa</option></select></Field><Field label="Valor *"><input value={form.valor} onChange={(e)=>setForm({...form,valor:e.target.value})} className={INPUT}/></Field><Field label="Vencimento *"><input type="date" value={form.vencimento} onChange={(e)=>setForm({...form,vencimento:e.target.value})} className={INPUT}/></Field><div className="flex items-end"><button disabled={save.isPending||form.descricao.length<3||parseMoney(form.valor)<=0||!form.vencimento} onClick={()=>save.mutate({descricao:form.descricao,credor:form.credor||undefined,categoria:form.categoria,valor:parseMoney(form.valor),vencimento:form.vencimento})} className="rounded-lg bg-blue-950 px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Salvar</button></div></div>}
    {query.isLoading?<Loading/>:<div className="space-y-2">{(query.data??[]).map((row)=><div key={row.id} className={`flex flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center ${row.id===targetId?"border-blue-400 bg-blue-50":"border-slate-200"}`}><div className="min-w-0 flex-1"><div className="text-sm font-bold text-slate-900">{row.descricao}</div><div className="mt-1 text-xs text-slate-500">{row.credor??row.categoria} · {formatBRL(Number(row.valor))} · vence {formatDateBR(row.vencimento)}</div></div>{!row.pagoEm&&<button disabled={paid.isPending} onClick={()=>paid.mutate({id:row.id})} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-bold text-emerald-700">Marcar pago</button>}</div>)}</div>}
  </Section>;
}

function Cashflow(){const query=trpc.posVenda.fluxoCaixa.useQuery();if(query.isLoading)return <Loading/>;const data=query.data;return <div className="mx-auto max-w-7xl space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="A receber" value={data?.aReceber??0}/><Metric label="A pagar" value={data?.aPagar??0}/><Metric label="Saldo projetado" value={data?.saldoProjetado??0}/></div>{((data?.atrasadosReceber??0)>0||(data?.atrasadosPagar??0)>0)&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-800">Atrasados: {formatBRL(data?.atrasadosReceber??0)} a receber · {formatBRL(data?.atrasadosPagar??0)} a pagar.</div>}<div className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="mb-3 text-sm font-black">Projeção mensal</h2><div className="space-y-2">{(data?.porMes??[]).map((row)=><div key={row.mes} className="grid grid-cols-4 gap-2 rounded-lg bg-slate-50 p-3 text-xs"><strong>{row.mes}</strong><span>Receber {formatBRL(row.receber)}</span><span>Pagar {formatBRL(row.pagar)}</span><span className="font-bold">Saldo {formatBRL(row.saldo)}</span></div>)}</div></div></div>}

const INPUT="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-blue-400";
function TabButton({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-bold ${active?"bg-blue-950 text-white":"bg-white text-slate-600"}`}>{label}</button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</span>{children}</label>}
function Section({title,icon,action,children}:{title:string;icon:React.ReactNode;action?:React.ReactNode;children:React.ReactNode}){return <section className="mx-auto max-w-7xl rounded-xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><span className="text-blue-900">{icon}</span><h2 className="m-0 text-sm font-black text-slate-900">{title}</h2><div className="ml-auto">{action}</div></div>{children}</section>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div><div className="mt-1 text-xl font-black text-slate-900">{formatBRL(value)}</div></div>}
function Loading(){return <div className="flex min-h-40 items-center justify-center text-slate-400"><Loader2 className="animate-spin" size={20}/></div>}
